export const PIN_IT_SERVER_URI = "https://pin-it-server-koushikkumarv.c9users.io";
export const TEST_AUTHORIZATION_URI = `${PIN_IT_SERVER_URI}/test-authorization`;
export const GENERATE_TOKEN_URI = `${PIN_IT_SERVER_URI}/generate-token`;
export const GET_OAUTH_TOKEN = `${PIN_IT_SERVER_URI}/get-oauth-token`;
export const FETCH_ALL_IMAGES_URI = "https://api.myjson.com/bins/pi6w5"; //TODO
export const DELETE_IMAGE_BY_ID_URI = "";//TODO
export const SAVE_IMAGE_URI="";//TODO
export const UNSAVE_IMAGE_URI = "";//TODO
export const ADD_IMAGE_URI = "";//TODO